"use client";
import AppShell from "@/components/AppShell";
import { db } from "@/lib/db";
import { KyraRuntime } from "@/lib/kyra-system/runtime";
import { useVault } from "@/lib/store";
import { useContinuousSpeech } from "@/lib/useContinuousSpeech";
import { playStopConfirmationChime } from "@/lib/voice/chime";
import { KyraVoiceEngine } from "@/lib/voice/engine";
import { initializeVoiceManager,useVoiceManager } from "@/lib/voice/manager";
import { voicePreferences } from "@/lib/voice/providers";
import { AlertTriangle,ArrowRight,Bug,Mic,MicOff,Settings,Sparkles,Volume2 } from "lucide-react";
import { useLiveQuery } from "dexie-react-hooks";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { useEffect,useRef,useState } from "react";

type KyraState="idle"|"starting"|"listening"|"thinking"|"speaking"|"error";
type Message={role:"user"|"kyra";text:string};

export default function Kyra(){
 const vault=useVault(),router=useRouter(),pathname=usePathname(),stored=useLiveQuery(()=>db.settings.toArray(),[],[])||[],settings=Object.fromEntries(stored.map(item=>[item.key,item.value]));
 const voiceManager=useVoiceManager(settings);
 const [active,setActive]=useState(false),[phase,setPhase]=useState<KyraState>("idle"),[input,setInput]=useState(""),[messages,setMessages]=useState<Message[]>([]),[notice,setNotice]=useState("");
 const busy=useRef(false),activeRef=useRef(false),awakeRef=useRef(false),greetedRef=useRef(false),interruptedRef=useRef(false),interruptChimeRef=useRef<Promise<void>|undefined>(undefined),messagesRef=useRef<Message[]>([]),voiceEngine=useRef(new KyraVoiceEngine()),runtime=useRef(new KyraRuntime()),lastSpoken=useRef("");
 const speech=useContinuousSpeech({language:(settings.recognitionLanguage||settings.language)==="hinglish"?"hi-IN":settings.recognitionLanguage||settings.language||"hi-IN",deviceId:settings.microphoneId,onFinal:handleTranscript,onLowConfidence:()=>{if(!busy.current)void speak("Sorry Kartik, ek baar phir bolna?")},onInterrupt:()=>{interruptedRef.current=true;voiceEngine.current.stop();interruptChimeRef.current=playStopConfirmationChime();setPhase("idle")}});
 const status:KyraState=(notice||speech.error||speech.permission==="denied")?"error":phase==="thinking"?"thinking":phase==="speaking"?"speaking":active&&speech.isStartingRecognition?"starting":active&&speech.isRecognitionRunning?"listening":"idle";
 useEffect(()=>{messagesRef.current=messages},[messages]);
 useEffect(()=>{activeRef.current=active},[active]);
 useEffect(()=>{const engine=voiceEngine.current;void db.settings.get("kyraConversation").then(saved=>{if(saved?.value)try{setMessages(JSON.parse(saved.value) as Message[])}catch{setMessages([])}});return()=>engine.stop()},[]);

 function handleTranscript(phrase:string){if(phase==="speaking")return;const command=phrase.trim().toLowerCase();if(/^(stop|cancel)$/.test(command)){stopAudio();busy.current=false;setPhase("idle");return}if(/^(be quiet|silent mode)$/.test(command)){stopAudio();void db.settings.put({key:"silentMode",value:"true"});setNotice("Silent Mode enabled. Say “Wake up” to resume.");return}if(/^(wake up|wake up kyra)$/.test(command)){void db.settings.put({key:"silentMode",value:"false"});awakeRef.current=true;void speak("I’m here.");return}if(/^(good night|sleep mode)$/.test(command)){void db.settings.put({key:"kyraVoiceDisabled",value:"true"});deactivate();return}if(busy.current)return;if(!awakeRef.current&&!/\b(hey|hi|hello)\s+kyra\b/i.test(phrase))return;if(!awakeRef.current){awakeRef.current=true;void answerWake(phrase);return}void ask(phrase)}
async function activate(auto=false){setNotice("");await initializeVoiceManager(settings);await db.settings.put({key:"kyraVoiceDisabled",value:"false"});awakeRef.current=auto;activeRef.current=true;setActive(true);setPhase("idle");const started=await speech.start();if(!started){activeRef.current=false;setActive(false);setPhase("error")}const greeted=sessionStorage.getItem("kyra_greeted_session")==="true";if(started&&auto&&!greetedRef.current&&!greeted){greetedRef.current=true;sessionStorage.setItem("kyra_greeted_session","true");busy.current=true;const hour=new Date().getHours(),greeting=hour<12?"Good morning Kartik.":hour<17?"Good afternoon Kartik.":"Good evening Kartik.";await speak(greeting);busy.current=false}}
 function deactivate(){speech.stop();stopAudio(false);busy.current=false;awakeRef.current=false;activeRef.current=false;setActive(false);setPhase("idle")}
 async function answerWake(heard:string){busy.current=true;const hindi=/namaste|namaskar/i.test(heard)||(settings.language==="hi-IN"),text=hindi?"Namaste Kartik, kaise ho?":"Hello Kartik, kaise ho?",next=[...messagesRef.current,{role:"user" as const,text:heard},{role:"kyra" as const,text}].slice(-40);saveMessages(next);await speak(text);busy.current=false;setPhase("idle")}
 async function ask(text:string){busy.current=true;setInput("");const prior=[...messagesRef.current,{role:"user" as const,text}];saveMessages(prior);setPhase("thinking");try{const history=prior.map(message=>({...message,createdAt:new Date().toISOString()})),result=await runtime.current.respond(text,pathname,vault.state,history),next=[...prior,{role:"kyra" as const,text:result.text}].slice(-40);saveMessages(next);await speak(result.text);if(result.navigate)router.push(result.navigate)}catch(error){const reply=error instanceof Error?error.message:"KYRA could not complete that request.";setNotice(reply);const next=[...prior,{role:"kyra" as const,text:reply}].slice(-40);saveMessages(next);await speak(reply)}finally{busy.current=false;setPhase("idle")}}
 function saveMessages(value:Message[]){messagesRef.current=value;setMessages(value);void db.settings.put({key:"kyraConversation",value:JSON.stringify(value)})}
 async function speak(text:string){if(settings.silentMode==="true")return;lastSpoken.current=text;interruptedRef.current=false;interruptChimeRef.current=undefined;speech.pauseForSpeech();setPhase("speaking");try{await voiceEngine.current.speak(text,voicePreferences(settings),{onStart:()=>{console.info("[KYRA] KYRA started speaking");setPhase("speaking")},onEnd:()=>{console.info("[KYRA] KYRA finished speaking");setPhase("idle")},onError:error=>console.warn("[KYRA] Speaking error",error)})}catch(error){setNotice(error instanceof Error?error.message:"KYRA voice playback failed.");setPhase("error")}finally{const interrupted=interruptedRef.current,chime:Promise<void>|undefined=interruptChimeRef.current;interruptedRef.current=false;interruptChimeRef.current=undefined;if(interrupted&&chime)try{await chime}catch(error){console.warn("[KYRA] Stop chime failed",error)}if(activeRef.current)speech.resumeAfterSpeech(interrupted?0:700)}}
 function stopAudio(resume=true){voiceEngine.current.stop();if(resume&&activeRef.current)speech.resumeAfterSpeech(700)}
 // Browser permission state is the intentional trigger; current settings are read when activation runs.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(voiceManager.ready&&speech.permission==="granted"&&!active&&settings.kyraVoiceDisabled!=="true")void activate(true)},[voiceManager.ready,speech.permission]);
 return <AppShell><div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-semibold text-violet-300">Karvian Intelligence & Reasoning Assistant</p><h1 className="mt-2 text-5xl font-black">KYRA</h1><p className="muted mt-2">Continuous Indian English, Hindi and Hinglish conversation.</p></div><Link className="btn2 flex items-center gap-2" href="/settings"><Settings size={17}/> Voice Settings</Link></div><section className="card mt-8 overflow-hidden"><div className={`kyra-stage ${status}`}><VoiceOrb status={status}/><StatusBadge status={status}/><h2 className="mt-5 text-2xl font-black">{label(status)}</h2><p className="muted mt-2 min-h-7 text-lg">{speech.interim||hint(status)}</p>{speech.permission==="denied"&&<PermissionHelp retry={()=>void speech.requestPermission()}/>} {(notice||speech.error)&&<p className="mt-4 max-w-xl rounded-2xl bg-red-500/10 px-4 py-2 text-sm text-red-300">{notice||speech.error}</p>}<button className={active?"btn2 mt-8 flex items-center gap-2":"btn mt-8 flex items-center gap-2"} onClick={active?deactivate:()=>void activate()}>{active?<><MicOff size={18}/> End Voice Mode</>:<><Mic size={18}/> Activate Continuous Voice</>}</button><Wave status={status}/></div><div className="grid gap-5 border-t border-white/10 p-5 lg:grid-cols-[1fr_300px]"><div className="max-h-72 space-y-3 overflow-auto pr-2">{messages.slice(-12).map((message,index)=><div key={index} className={`max-w-[85%] rounded-2xl p-3 text-sm ${message.role==="user"?"ml-auto bg-violet-500/20":"bg-white/5"}`}><b className="mb-1 block text-xs text-violet-300">{message.role==="user"?"You":"KYRA"}</b>{message.text}</div>)}</div><div><b className="mb-3 block text-sm">Try saying</b>{["Hey Kyra","Password Vault open karo","Aaj mera schedule batao","What tasks are pending?"].map(prompt=><button key={prompt} onClick={()=>handleTranscript(prompt)} className="mb-2 flex w-full items-center justify-between rounded-xl bg-white/5 p-3 text-left text-sm">{prompt}<ArrowRight size={14}/></button>)}</div></div><form className="flex gap-3 border-t border-white/10 p-5" onSubmit={event=>{event.preventDefault();if(input.trim())void ask(input.trim())}}><input className="field" value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask KYRA anything…"/><button className="btn"><Sparkles size={18}/></button></form><DebugPanel logs={speech.logs}/></section></div></AppShell>
}

function PermissionHelp({retry}:{retry:()=>void}){return <div className="mt-5 max-w-xl rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-left"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-red-300"/><div><b>Microphone access is blocked</b><p className="muted mt-1 text-sm">Open the lock icon beside the address bar, go to Site settings, set Microphone to Allow, then reload this page.</p><button className="btn2 mt-3" onClick={retry}>Try Again</button></div></div></div>}
function StatusBadge({status}:{status:KyraState}){const value=status==="starting"?["🟡","Starting microphone"]:status==="listening"?["🟢","Listening"]:status==="thinking"?["🟡","Thinking"]:status==="speaking"?["🔴","Speaking"]:status==="error"?["🔴","Error"]:["⚪","Idle"];return <div className="mt-6 rounded-full border border-white/10 bg-black/20 px-4 py-2 text-sm font-bold">{value[0]} {value[1]}</div>}
function VoiceOrb({status}:{status:KyraState}){return <div className={`kyra-orb ${status}`}><div className="kyra-core">{status==="speaking"?<Volume2 size={38}/>:<Mic size={38}/>}</div><span/><span/><span/><i/><i/></div>}
function Wave({status}:{status:KyraState}){return <div className="mt-5 flex h-12 items-center gap-1">{Array.from({length:36},(_,index)=><span key={index} className={`voice-bar ${status}`} style={{animationDelay:`${index*28}ms`}}/>)}</div>}
function DebugPanel({logs}:{logs:{id:string;time:string;message:string;detail?:string}[]}){return <details className="border-t border-white/10 p-5 text-sm"><summary className="flex cursor-pointer items-center gap-2 font-bold"><Bug size={16}/> Voice Debug Log</summary><div className="mt-3 max-h-48 overflow-auto rounded-xl bg-black/20 p-3 font-mono text-xs">{logs.length?logs.map(log=><div key={log.id}><span className="muted">[{log.time}]</span> {log.message} {log.detail&&`— ${log.detail}`}</div>):"No voice events yet."}</div></details>}
function label(status:KyraState){return status==="starting"?"Starting microphone":status==="listening"?"I’m listening":status==="thinking"?"Thinking":status==="speaking"?"Speaking":status==="error"?"Voice needs attention":"KYRA is ready"}
function hint(status:KyraState){return status==="starting"?"Getting the microphone ready…":status==="listening"?"Speak naturally. Live words appear here.":status==="thinking"?"One moment…":status==="speaking"?"Microphone is paused while I speak.":"Activate once for a continuous conversation."}
