"use client";
import AppShell from "@/components/AppShell";
import { ProgressBar,StatCard } from "@/components/UI";
import { db } from "@/lib/db";
import { demoActivitiesFor,useVault } from "@/lib/store";
import { isDemoMode } from "@/lib/appMode";
import { useLiveQuery } from "dexie-react-hooks";
import { Bot,CheckCircle2,FileText,FolderKanban,KeyRound,NotebookPen,SquareCheckBig } from "lucide-react";
import Link from "next/link";
import { Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";

const actions=[["/projects","Projects",FolderKanban],["/tasks","Tasks",SquareCheckBig],["/notes","Notes",NotebookPen],["/documents","Documents",FileText],["/ai-vault","AI Library",Bot],["/vault","Vault Preview",KeyRound]] as const;
const tooltipStyle={background:"#0d1020",border:"1px solid rgba(255,255,255,.12)",borderRadius:12};

export default function Dashboard(){
 const vault=useVault(),liveActivities=useLiveQuery(()=>isDemoMode?Promise.resolve(demoActivitiesFor().slice(0,6)):db.activities.orderBy("createdAt").reverse().limit(6).toArray(),[],[])||[],activities=isDemoMode?demoActivitiesFor().slice(0,6):liveActivities;
 const projects=vault.state.projects.filter(p=>!p.archivedAt),open=vault.state.tasks.filter(t=>t.status!=="done"),done=vault.state.tasks.filter(t=>t.status==="done"),today=new Date().toISOString().slice(0,10);
 const upcoming=[...open].filter(t=>t.due>=today).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5),focus=[...open].sort((a,b)=>priorityValue(b.priority)-priorityValue(a.priority)||a.due.localeCompare(b.due)).slice(0,5);
 const statusData=[{name:"Completed",value:done.length,color:"#34d399"},{name:"Open",value:open.length,color:"#8b5cf6"}],projectData=projects.slice(0,6).map(p=>({name:p.name.length>12?`${p.name.slice(0,12)}...`:p.name,progress:p.progress}));
 return <AppShell>
  <section className="mb-8 overflow-hidden rounded-[2rem] border border-cyan-300/20 bg-gradient-to-br from-cyan-400/10 via-violet-500/10 to-transparent p-6 shadow-[0_0_50px_rgba(34,211,238,.08)]">
   <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end">
    <div><span className="inline-flex rounded-full border border-cyan-300/30 bg-cyan-400/10 px-3 py-1 text-xs font-black tracking-[.28em] text-cyan-200">PUBLIC DEMO</span><p className="mt-4 text-sm font-semibold text-violet-300">KARVIAN VAULT SHOWCASE · {new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long"})}</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Explore Karvian Vault.</h1><p className="muted mt-2 max-w-2xl">This is a safe read-only public showcase with sample projects, tasks, notes, documents, vault previews, and KYRA UI. No private data or Gemini quota is used.</p></div>
    <Link href="/jarvis" className="btn">Preview KYRA</Link>
   </div>
  </section>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Demo Projects" value={projects.length} icon={<FolderKanban className="text-violet-300"/>}/><StatCard label="Sample Tasks" value={open.length} icon={<SquareCheckBig className="text-orange-300"/>}/><StatCard label="Completed Samples" value={done.length} icon={<CheckCircle2 className="text-green-300"/>}/><StatCard label="Locked Vault Items" value={vault.state.credentials.length} icon={<KeyRound className="text-cyan-300"/>}/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><Panel title="Demo Projects"><div className="space-y-4">{projects.slice(0,5).map(p=><Link key={p.id} href={`/projects/${p.id}`} className="block rounded-2xl border border-white/10 bg-white/5 p-4"><div className="mb-2 flex justify-between"><b>{p.name}</b><span className="muted text-sm">{p.progress}%</span></div><ProgressBar value={p.progress}/></Link>)}{!projects.length&&<p className="muted">No demo projects.</p>}</div></Panel><Panel title="Sample Focus"><div className="space-y-3">{focus.map(t=><Link href="/tasks" key={t.id} className="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><span className={`h-2.5 w-2.5 rounded-full ${t.priority==="critical"?"bg-red-400":t.priority==="high"?"bg-orange-400":"bg-violet-400"}`}/><div className="min-w-0"><p className="truncate font-semibold">{t.title}</p><p className="muted text-xs">{t.due} · {t.priority}</p></div></Link>)}{!focus.length&&<p className="muted">The demo queue is clear.</p>}</div></Panel><Panel title="Upcoming Demo Deadlines"><div className="space-y-3">{upcoming.map(t=><div key={t.id} className="flex items-center gap-3 border-b border-white/10 pb-3"><div className="rounded-xl bg-violet-500/10 px-3 py-2 text-center"><small className="text-violet-300">{new Date(`${t.due}T00:00:00`).toLocaleDateString("en",{month:"short"})}</small><b className="block">{t.due.slice(-2)}</b></div><p className="font-semibold">{t.title}</p></div>)}{!upcoming.length&&<p className="muted">No upcoming demo deadlines.</p>}</div></Panel></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><Panel title="Weekly Demo Productivity"><Chart><ResponsiveContainer><LineChart data={weeklyData(vault.state.tasks)}><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false}/><XAxis dataKey="day"/><YAxis allowDecimals={false}/><Tooltip contentStyle={tooltipStyle}/><Line type="monotone" dataKey="completed" stroke="#8b5cf6" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart></Panel><Panel title="Task Completion"><Chart><ResponsiveContainer><PieChart><Pie data={statusData} dataKey="value" innerRadius={58} outerRadius={82}>{statusData.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer></Chart></Panel><Panel title="Project Progress"><Chart><ResponsiveContainer><BarChart data={projectData}><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false}/><XAxis dataKey="name" fontSize={11}/><YAxis domain={[0,100]}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="progress" fill="#22d3ee" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Chart></Panel></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><Panel title="Recent Sample Knowledge"><Recent icon={<Bot size={16}/>} items={vault.state.chats.slice(0,3).map(x=>x.title)} empty="No AI chats"/><Recent icon={<NotebookPen size={16}/>} items={vault.state.notes.slice(0,3).map(x=>x.title)} empty="No notes"/><Recent icon={<FileText size={16}/>} items={vault.state.documents.slice(0,3).map(x=>x.name)} empty="No documents"/></Panel><Panel title="Demo Activity">{activities.length?activities.map(a=><div key={a.id} className="border-b border-white/10 py-3"><b>{a.action}</b><p className="muted text-xs">{relativeTime(a.createdAt)}</p></div>):<p className="muted">Activity will appear as you explore.</p>}</Panel><Panel title="Explore Public Demo"><div className="grid grid-cols-2 gap-3">{actions.map(([href,label,Icon])=><Link className="flex flex-col items-center gap-2 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm font-semibold" href={href} key={label}><Icon className="text-violet-300"/>{label}</Link>)}</div></Panel></div>
  <section className="card mt-6 flex items-center gap-5 p-6"><div className="orb !h-16 !w-16 shrink-0"/><div><span className="badge">KYRA Demo Insight</span><p className="mt-3 text-lg font-semibold">Public Demo Mode uses scripted safe responses and sample Vault context. Interactive Gemini reasoning is available only in the private owner version.</p></div></section>
 </AppShell>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-5"><h2 className="mb-5 text-xl font-black">{title}</h2>{children}</section>}
function Chart({children}:{children:React.ReactNode}){return <div className="h-64">{children}</div>}
function Recent({icon,items,empty}:{icon:React.ReactNode;items:string[];empty:string}){return <div className="mb-3 space-y-2">{items.length?items.map((item,i)=><div className="flex items-center gap-2 text-sm" key={`${item}-${i}`}>{icon}<span className="truncate">{item}</span></div>):<p className="muted text-sm">{empty}</p>}</div>}
function priorityValue(v:string){return v==="critical"?4:v==="high"?3:v==="medium"?2:1}
function relativeTime(v:string){const m=Math.floor((Date.now()-new Date(v).getTime())/60000);return m<1?"just now":m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`}
function weeklyData(tasks:{status:string;updatedAt:string}[]){return Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=d.toISOString().slice(0,10);return {day:d.toLocaleDateString("en",{weekday:"short"}),completed:tasks.filter(t=>t.status==="done"&&t.updatedAt.slice(0,10)===key).length}})}
