"use client";

import { isDemoMode } from "@/lib/appMode";
import { useVault } from "@/lib/store";
import { BarChart3,Bot,Brain,CalendarDays,FileText,FolderKanban,Home,KeyRound,Menu,Mic,NotebookPen,Search,Settings,ShieldCheck,SquareCheckBig,X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

const navigation=[["/","Dashboard",Home],["/projects","Projects",FolderKanban],["/tasks","Tasks",SquareCheckBig],["/ai-vault","AI Library",Bot],["/memory","AI Memory",Brain],["/vault","Password Vault",KeyRound],["/notes","Notes",NotebookPen],["/documents","Documents",FileText],["/calendar","Calendar",CalendarDays],["/reports","Reports",BarChart3],["/settings","Settings",Settings]] as const;

function Sidebar({close}:{close?:()=>void}){
 const pathname=usePathname();
 return <><div className="flex items-center justify-between px-2 py-3"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-500/20 text-violet-300"><ShieldCheck/></div><div><div className="text-xl font-black">Karvian Vault</div><div className="text-xs muted">KYRA Founder OS</div></div></div>{close&&<button className="btn2" aria-label="Close navigation" onClick={close}><X size={18}/></button>}</div>{isDemoMode&&<div className="mt-3 rounded-2xl border border-cyan-300/25 bg-cyan-400/10 p-3"><div className="text-xs font-black tracking-[.28em] text-cyan-200">PUBLIC DEMO</div><p className="muted mt-2 text-xs">Read-only showcase with safe sample data.</p></div>}<nav className="mt-7 space-y-1">{navigation.map(([href,label,Icon])=>{const active=href==="/"?pathname===href:pathname.startsWith(href);return <Link onClick={close} key={href} href={href} className={`flex items-center gap-3 rounded-2xl px-4 py-2.5 text-sm font-semibold transition ${active?"border border-violet-400/20 bg-violet-500/20 text-white":"text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon size={18}/>{label}</Link>})}</nav><Link href="/jarvis" onClick={close} className="absolute bottom-5 left-5 right-5 rounded-3xl border border-violet-400/20 bg-violet-500/10 p-4"><div className="flex items-center gap-3"><div className="orb !h-12 !w-12"/><div><div className="font-bold">KYRA Voice Mode</div><div className="text-xs muted">{isDemoMode?"Demo preview":"Continuous assistant"}</div></div></div></Link></>
}

export default function AppShell({children}:{children:React.ReactNode}){
 const [menu,setMenu]=useState(false),[query,setQuery]=useState("");
 const {state}=useVault(),term=query.trim().toLowerCase();
 const results=term?[...state.projects.filter(item=>!item.archivedAt).map(item=>({label:item.name,sub:"Project",href:`/projects/${item.id}`})),...state.tasks.map(item=>({label:item.title,sub:"Task",href:"/tasks"})),...state.notes.map(item=>({label:item.title,sub:"Note",href:"/notes"})),...state.documents.map(item=>({label:item.name,sub:"Document",href:"/documents"})),...state.chats.map(item=>({label:item.title,sub:item.model,href:"/ai-vault"}))].filter(item=>item.label.toLowerCase().includes(term)).slice(0,8):[];
 return <div className="relative flex min-h-screen"><aside className="fixed left-0 top-0 z-20 hidden h-screen w-72 border-r border-white/10 bg-[#070812]/80 p-5 backdrop-blur-xl lg:block"><Sidebar/></aside>{menu&&<div className="fixed inset-0 z-40 bg-black/70 lg:hidden" onClick={()=>setMenu(false)}><aside className="relative h-full w-72 border-r border-white/10 bg-[#070812] p-5" onClick={event=>event.stopPropagation()}><Sidebar close={()=>setMenu(false)}/></aside></div>}<main className="w-full lg:pl-72"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#070812]/80 backdrop-blur-xl"><div className="flex items-center gap-3 px-5 py-4 lg:px-8"><button className="btn2 lg:hidden" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={18}/></button>{isDemoMode&&<span className="hidden rounded-full border border-cyan-300/30 bg-cyan-400/10 px-3 py-2 text-xs font-black tracking-[.24em] text-cyan-200 md:inline">PUBLIC DEMO</span>}<div className="relative max-w-xl flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input className="field pl-10" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search the entire Vault..."/>{term&&<div className="glass absolute left-0 right-0 top-14 overflow-hidden rounded-2xl">{results.length?results.map((result,index)=><Link key={`${result.href}-${index}`} href={result.href} onClick={()=>setQuery("")} className="block border-b border-white/10 px-4 py-3 last:border-0 hover:bg-white/5"><span className="font-semibold">{result.label}</span><span className="muted ml-2 text-xs">{result.sub}</span></Link>):<p className="muted p-4 text-sm">No matches</p>}</div>}</div>{isDemoMode&&<a href="https://www.linkedin.com/in/kartikeya-garg" target="_blank" rel="noreferrer" className="btn2 hidden sm:inline-flex">Built by Kartikeya Garg</a>}<Link href="/jarvis" className="btn2 flex items-center gap-2"><Mic size={18}/><span className="hidden sm:inline">Talk to KYRA</span></Link></div></header>{isDemoMode&&<div className="border-b border-cyan-300/15 bg-cyan-400/5 px-5 py-3 text-sm text-cyan-100 lg:px-8"><b>Public Demo:</b> sample data only. Create, edit, delete, upload, Gemini, and secret APIs are disabled.</div>}<div className="p-5 lg:p-8">{children}</div></main><Link href="/jarvis" aria-label="Open KYRA" className="fixed bottom-6 right-6 z-30 flex h-16 w-16 items-center justify-center rounded-full border border-violet-300/30 bg-gradient-to-br from-violet-500 to-indigo-700 shadow-[0_0_40px_rgba(139,92,246,.55)] transition hover:scale-105"><Mic/></Link></div>
}
