"use client";
import { db } from "@/lib/db";
import { KyraRuntime } from "@/lib/kyra-system/runtime";
import type { KyraMessage } from "@/lib/kyra-system/types";
import { useVault } from "@/lib/store";
import { useContinuousSpeech } from "@/lib/useContinuousSpeech";
import { playStopConfirmationChime } from "@/lib/voice/chime";
import { KyraVoiceEngine } from "@/lib/voice/engine";
import { initializeVoiceManager,useVoiceManager } from "@/lib/voice/manager";
import { voicePreferences } from "@/lib/voice/providers";
import { Mic,MicOff } from "lucide-react";
import { useLiveQuery } from "dexie-react-hooks";
import { usePathname,useRouter } from "next/navigation";
import { useEffect,useRef,useState } from "react";

type KyraPhase="idle"|"thinking"|"speaking"|"error";

export default function KyraAlwaysActive(){
 const pathname=usePathname(),router=useRouter(),vault=useVault(),rows=useLiveQuery(()=>db.settings.toArray(),[],[])||[],settings=Object.fromEntries(rows.map(row=>[row.key,row.value])),[active,setActive]=useState(false),[phase,setPhase]=useState<KyraPhase>("idle");
 const voiceManager=useVoiceManager(settings);
 const interruptRef=useRef(false),interruptChimeRef=useRef<Promise<void>|undefined>(undefined),startupWelcomeRef=useRef(false),runtime=useRef(new KyraRuntime()),voice=useRef(new KyraVoiceEngine()),messages=useRef<KyraMessage[]>([]),busy=useRef(false),activeRef=useRef(false),greetedRef=useRef(false),speech=useContinuousSpeech({language:recognitionLanguage(settings),deviceId:settings.microphoneId,onFinal:handle,onLowConfidence:()=>{if(!busy.current)void say("Sorry Kartik, ek baar phir bolna?")},onInterrupt:()=>{interruptRef.current=true;voice.current.stop();interruptChimeRef.current=playStopConfirmationChime();setPhase("idle")}});
 const pageOwnsVoice=pathname==="/jarvis";
 useEffect(()=>{activeRef.current=active},[active]);
 useEffect(()=>{const engine=voice.current;void runtime.current.conversation.load().then(value=>{messages.current=value});return()=>engine.stop()},[]);
 async function start(auto=false){if(pageOwnsVoice)return;await initializeVoiceManager(settings);activeRef.current=true;setActive(true);setPhase("idle");const okay=await speech.start();if(!okay){activeRef.current=false;setActive(false);setPhase("error")}const greeted=sessionStorage.getItem("kyra_greeted_session")==="true";if(okay&&startupWelcomeRef.current){await speakStartupWelcome();return}if(sessionStorage.getItem("karvian_startup_active")==="true")return;if(okay&&auto&&!greetedRef.current&&!greeted){greetedRef.current=true;sessionStorage.setItem("kyra_greeted_session","true");const hour=new Date().getHours(),now=Date.now(),week=now+7*86400000,deadlines=vault.state.tasks.filter(task=>task.status!=="done"&&new Date(`${task.due}T23:59:59`).getTime()>=now&&new Date(`${task.due}T23:59:59`).getTime()<=week).length,inactive=vault.state.projects.find(project=>!project.archivedAt&&now-new Date(project.updatedAt).getTime()>2*86400000),hello=hour<12?"Good morning Kartik.":hour<17?"Good afternoon Kartik.":"Good evening Kartik.",insight=deadlines?` You have ${deadlines} deadline${deadlines===1?"":"s"} this week.`:inactive?` ${inactive.name} has not been updated for a few days.`:"";await say(`${hello}${insight}`)}}
 async function speakStartupWelcome(){if(greetedRef.current||sessionStorage.getItem("kyra_greeted_session")==="true")return;startupWelcomeRef.current=false;greetedRef.current=true;sessionStorage.setItem("kyra_greeted_session","true");busy.current=true;await say("Welcome back, Kartik.");busy.current=false;setPhase("idle")}
 async function handle(input:string){if(phase==="speaking")return;const command=input.trim().toLowerCase();if(/^(stop|cancel)$/.test(command)){voice.current.stop();busy.current=false;setPhase("idle");return}if(/^(be quiet|silent mode)$/.test(command)){voice.current.stop();await db.settings.put({key:"silentMode",value:"true"});return}if(/^(wake up|wake up kyra)$/.test(command)){await db.settings.put({key:"silentMode",value:"false"});await say("I’m here.",{...settings,silentMode:"false"});return}if(/^(good night|sleep mode)$/.test(command)){await db.settings.put({key:"kyraVoiceDisabled",value:"true"});speech.stop();activeRef.current=false;setActive(false);setPhase("idle");return}if(busy.current)return;busy.current=true;setPhase("thinking");messages.current=runtime.current.conversation.append(messages.current,"user",input);try{const result=await runtime.current.respond(input,pathname,vault.state,messages.current);messages.current=runtime.current.conversation.append(messages.current,"kyra",result.text);await runtime.current.conversation.save(messages.current);await say(result.text);if(result.navigate)router.push(result.navigate)}finally{busy.current=false;setPhase("idle")}}
 async function say(text:string,override?:Record<string,string>){const prefs=override||settings;if(prefs.silentMode==="true"){if(activeRef.current)speech.resumeAfterSpeech(700);return}interruptRef.current=false;interruptChimeRef.current=undefined;speech.pauseForSpeech();setPhase("speaking");try{await voice.current.speak(text,voicePreferences(prefs),{onStart:()=>setPhase("speaking"),onEnd:()=>setPhase("idle"),onError:error=>console.warn("[KYRA] Speaking error",error)})}catch(error){console.warn("[KYRA] Speaking failed",error);setPhase("error")}finally{const interrupted=interruptRef.current,chime:Promise<void>|undefined=interruptChimeRef.current;interruptRef.current=false;interruptChimeRef.current=undefined;if(interrupted&&chime)try{await chime}catch(error){console.warn("[KYRA] Stop chime failed",error)}if(activeRef.current)speech.resumeAfterSpeech(interrupted?0:700)}}
 // Permission and route transitions intentionally drive the global runtime lifecycle.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(pageOwnsVoice){speech.stop();activeRef.current=false;setActive(false);setPhase("idle");return}if(voiceManager.ready&&speech.permission==="granted"&&settings.kyraVoiceDisabled!=="true"&&!active)void start(true)},[pageOwnsVoice,voiceManager.ready,speech.permission]);
 useEffect(()=>{function onStartupComplete(){startupWelcomeRef.current=true;if(activeRef.current&&!pageOwnsVoice)void speakStartupWelcome()}window.addEventListener("karvian:startup-complete",onStartupComplete);return()=>window.removeEventListener("karvian:startup-complete",onStartupComplete)},[pageOwnsVoice]);
 if(pageOwnsVoice)return null;
 if(speech.permission==="prompt"||speech.permission==="denied")return <button className="fixed bottom-6 right-24 z-40 flex items-center gap-2 rounded-full border border-violet-400/30 bg-[#101326]/95 px-4 py-3 text-sm font-bold shadow-xl" onClick={()=>void start()}><Mic size={17}/>{speech.permission==="denied"?"Enable mic in browser":"Enable KYRA"}</button>;
 const label=phase==="thinking"?"Thinking":phase==="speaking"?"Speaking":phase==="error"?"Error":active&&speech.isStartingRecognition?"Starting":active&&speech.isRecognitionRunning?"Listening":active?"Idle":"Off";
 return <button title={speech.error||"KYRA always-active voice"} className="fixed bottom-6 right-24 z-40 flex items-center gap-2 rounded-full border border-violet-400/30 bg-[#101326]/95 px-4 py-3 text-sm font-bold shadow-xl" onClick={()=>{if(active){speech.stop();activeRef.current=false;setActive(false);setPhase("idle")}else void start()}}>{active?<Mic size={17} className={phase==="speaking"?"text-red-400":phase==="thinking"||speech.isStartingRecognition?"text-yellow-300":phase==="error"?"text-red-400":speech.isRecognitionRunning?"text-green-400":"text-slate-400"}/>:<MicOff size={17}/>} KYRA {label}</button>;
}
function recognitionLanguage(settings:Record<string,string>){const value=settings.recognitionLanguage||settings.language||"hi-IN";return value==="hinglish"?"hi-IN":value}
