"use client";
import AppShell from "@/components/AppShell";
import { PageTitle } from "@/components/UI";
import { VoiceSettings } from "@/components/VoiceSettings";
import { isDemoMode,demoWriteMessage } from "@/lib/appMode";
import { db } from "@/lib/db";
import { demoMemories } from "@/lib/demoData";
import { exportVault,resetVault } from "@/lib/store";
import type { Setting } from "@/lib/types";
import { useLiveQuery } from "dexie-react-hooks";
import { useEffect,useState } from "react";

export default function Settings(){
 const stored=useLiveQuery(()=>isDemoMode?Promise.resolve([] as Setting[]):db.settings.toArray(),[],[])||[],storedMemoryCount=useLiveQuery(()=>isDemoMode?Promise.resolve(demoMemories.length):db.memories.count(),[],0)||0,memoryCount=isDemoMode?demoMemories.length:storedMemoryCount,[message,setMessage]=useState(""),[configured,setConfigured]=useState(false),settings=Object.fromEntries(stored.map(item=>[item.key,item.value]));
 useEffect(()=>{if(isDemoMode){setConfigured(false);return}void fetch("/api/kyra").then(response=>response.json()).then(data=>setConfigured(Boolean(data.configured))).catch(()=>setConfigured(false))},[]);
 async function set(key:string,value:string){if(isDemoMode){setMessage(demoWriteMessage);return}await db.settings.put({key,value});if(key==="theme")document.documentElement.dataset.theme=value;if(key==="showStartupSequence"&&value==="true")sessionStorage.removeItem("karvian_startup_seen_v3")}
 async function download(){const data=await exportVault(),blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`karvian-vault-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url)}
 async function restore(file:File){if(isDemoMode){void file;setMessage(demoWriteMessage);return}try{const data=JSON.parse(await file.text()) as Record<string,unknown[]>;await db.transaction("rw",db.tables,async()=>{for(const table of db.tables){const rows=data[table.name];if(Array.isArray(rows)){await table.clear();await table.bulkPut(rows)}}});setMessage("Backup restored successfully.")}catch{setMessage("That backup could not be restored.")}}
 return <AppShell><PageTitle title="Settings" subtitle="Configure KYRA, voice, privacy and local workspace controls."/>{message&&<p className="mb-5 rounded-2xl bg-violet-500/10 p-4">{message}</p>}<div className="grid gap-5 md:grid-cols-2"><VoiceSettings settings={settings}/><Section title="Appearance"><label className="muted text-sm">Theme</label><select className="field mt-2" value={settings.theme||"obsidian"} onChange={event=>void set("theme",event.target.value)}><option value="obsidian">Obsidian Violet</option><option value="midnight">Midnight Blue</option></select><label className="mt-5 flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><span><b>Show startup sequence</b><small className="muted mt-1 block">Play the cinematic Karvian Vault boot intro once per browser session.</small></span><input type="checkbox" className="h-5 w-5 accent-violet-500" checked={settings.showStartupSequence!=="false"} onChange={event=>void set("showStartupSequence",event.target.checked?"true":"false")}/></label></Section><Section title="Gemini Intelligence"><div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${configured?"bg-green-400":"bg-orange-400"}`}/><p className="font-semibold">{configured?"Gemini brain connected":"Local intelligence only"}</p></div><p className="muted mt-3 text-sm">Add <code>GEMINI_API_KEY</code> to <code>.env.local</code>. Keys never enter the browser.</p></Section><Section title="AI Memory"><p className="muted">KYRA has {memoryCount} memory records plus persistent recent conversation context.</p><button className="btn2 mt-4 text-red-300" onClick={()=>confirm("Forget all AI memories and conversation history?")&&void Promise.all([db.memories.clear(),db.settings.delete("kyraConversation")])}>Forget Memory</button></Section><Section title="Backup & Restore"><p className="muted">Export or replace local Vault data.</p><div className="mt-5 flex gap-3"><button className="btn" onClick={()=>void download()}>Export</button><label className="btn2 cursor-pointer">Import<input className="hidden" type="file" accept="application/json" onChange={event=>{const file=event.target.files?.[0];if(file&&confirm("Replace current data?"))void restore(file)}}/></label></div></Section><Section title="Danger Zone"><p className="muted">Permanently clear this browser&apos;s Vault.</p><button className="btn2 mt-5 text-red-300" onClick={()=>confirm("Permanently delete all Vault data?")&&void resetVault().then(()=>setMessage("Vault cleared."))}>Clear Vault</button></Section></div></AppShell>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-6"><h2 className="mb-4 text-xl font-black">{title}</h2>{children}</section>}
