"use client";
import AppShell from "@/components/AppShell";
import { ProgressBar,StatCard } from "@/components/UI";
import { db } from "@/lib/db";
import { demoActivitiesFor,useVault } from "@/lib/store";
import { isDemoMode } from "@/lib/appMode";
import { useLiveQuery } from "dexie-react-hooks";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { useState } from "react";

const tabs=["overview","tasks","notes","documents","secrets","ai chats","timeline","analytics","settings"] as const;
type Tab=typeof tabs[number];
export default function Workspace(){
 const {id}=useParams<{id:string}>(),router=useRouter(),vault=useVault(),[tab,setTab]=useState<Tab>("overview"),project=vault.state.projects.find(item=>item.id===id),liveActivities=useLiveQuery(()=>isDemoMode?Promise.resolve(demoActivitiesFor(id)):db.activities.filter(item=>item.entityId===id).toArray().then(items=>items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))),[id],[])||[],activities=isDemoMode?demoActivitiesFor(id):liveActivities;
 if(!project)return <AppShell><div className="card p-8">Project not found. <Link className="underline" href="/projects">Back to projects</Link></div></AppShell>;
 const tasks=vault.state.tasks.filter(item=>item.projectId===id),notes=vault.state.notes.filter(item=>item.projectId===id),chats=vault.state.chats.filter(item=>item.projectId===id),credentials=vault.state.credentials.filter(item=>item.projectId===id),documents=vault.state.documents.filter(item=>item.projectId===id),done=tasks.filter(item=>item.status==="done").length;
 return <AppShell><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-5xl font-black">{project.name}</h1><span className="badge">{project.status}</span><span className="badge">{project.priority}</span></div><p className="muted mt-2 max-w-3xl">{project.description}</p></div><div className="flex gap-2"><button className="btn2" onClick={()=>void vault.archiveProject(id).then(()=>router.push("/projects"))}>Archive</button><Link className="btn" href="/jarvis">Ask KYRA</Link></div></div><div className="mb-6 flex gap-2 overflow-x-auto pb-2">{tabs.map(value=><button key={value} className={tab===value?"btn whitespace-nowrap":"btn2 whitespace-nowrap"} onClick={()=>setTab(value)}>{value.replace(/^./,letter=>letter.toUpperCase())}</button>)}</div>
 {tab==="overview"&&<div className="space-y-6"><section className="card p-5"><div className="mb-2 flex justify-between text-sm muted"><span>Project Progress</span><span>{project.progress}%</span></div><ProgressBar value={project.progress}/><div className="mt-4 flex justify-between gap-4"><p className="muted">{project.aiSummary||"Add KYRA context from the Projects editor."}</p><button className="btn2" onClick={()=>void vault.updateProject(id,{progress:Math.min(100,project.progress+5)})}>+5%</button></div></section><div className="grid gap-4 md:grid-cols-4"><StatCard label="Tasks" value={tasks.length}/><StatCard label="Notes" value={notes.length}/><StatCard label="Documents" value={documents.length}/><StatCard label="AI Chats" value={chats.length}/></div></div>}
 {tab==="tasks"&&<Collection title="Project Tasks" href="/tasks" empty="No linked tasks." items={tasks.map(item=>`${item.title} · ${item.status} · ${item.due}`)}/>} {tab==="notes"&&<Collection title="Project Notes" href="/notes" empty="No linked notes." items={notes.map(item=>item.title)}/>} {tab==="documents"&&<Collection title="Project Documents" href="/documents" empty="No linked documents." items={documents.map(item=>item.name)}/>} {tab==="secrets"&&<Collection title="Encrypted Credentials" href="/vault" empty="No linked secrets." items={credentials.map(item=>`${item.name} · ${item.category}`)}/>} {tab==="ai chats"&&<Collection title="GPT & Claude Chats" href="/ai-vault" empty="No linked chats." items={chats.map(item=>`${item.model} · ${item.title}`)}/>} 
 {tab==="timeline"&&<section className="card p-6"><h2 className="text-2xl font-black">Timeline</h2><div className="mt-5 space-y-4">{activities.length?activities.map(item=><div key={item.id} className="border-l-2 border-violet-500 pl-4"><b>{item.action}</b><p className="muted text-sm">{new Date(item.createdAt).toLocaleString()}</p></div>):<p className="muted">Project activity will appear here.</p>}</div></section>}
 {tab==="analytics"&&<div className="grid gap-4 md:grid-cols-3"><StatCard label="Completion Rate" value={`${tasks.length?Math.round(done/tasks.length*100):0}%`}/><StatCard label="Open Tasks" value={tasks.length-done}/><StatCard label="Knowledge Items" value={notes.length+documents.length+chats.length}/></div>}
 {tab==="settings"&&<section className="card max-w-2xl p-6"><h2 className="text-2xl font-black">Workspace Settings</h2><p className="muted mt-2">Edit project identity and KYRA context from Projects, or permanently remove this workspace and every linked record.</p><div className="mt-5 flex gap-3"><Link href="/projects" className="btn">Edit Project</Link><button className="btn2 text-red-300" onClick={()=>confirm(`Permanently delete ${project.name}?`)&&void vault.deleteProject(id).then(()=>router.push("/projects"))}>Delete Workspace</button></div></section>}
 </AppShell>
}
function Collection({title,href,items,empty}:{title:string;href:string;items:string[];empty:string}){return <section className="card p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><Link className="btn2" href={href}>Manage</Link></div><div className="mt-5 space-y-3">{items.length?items.map((item,index)=><div className="rounded-2xl bg-white/5 p-4 font-semibold" key={`${item}-${index}`}>{item}</div>):<p className="muted">{empty}</p>}</div></section>}
