import { NextResponse } from "next/server";
import { isDemoMode } from "@/lib/appMode";
import type { VoiceProviderId } from "@/lib/voice/types";

type SpeechRequest={text?:string;provider?:VoiceProviderId;voice?:string;speed?:number;pitch?:number;volume?:number;language?:string};
export async function POST(request:Request){
 if(isDemoMode)return NextResponse.json({error:"Server speech synthesis is disabled in Public Demo Mode.",demo:true},{status:403});
 const input=await request.json() as SpeechRequest;if(!input.text?.trim())return NextResponse.json({error:"Text is required."},{status:400});
 const provider=input.provider||defaultProvider();
 try{if(provider==="elevenlabs")return await elevenLabs(input);if(provider==="azure")return await azure(input);if(provider==="openai")return await openAi(input);return NextResponse.json({error:"Browser speech is synthesized on the client."},{status:400})}catch(error){console.error(`${provider} speech error`,error);return NextResponse.json({error:`${provider} speech generation failed.`},{status:502})}
}
function defaultProvider():VoiceProviderId{if(process.env.ELEVENLABS_API_KEY)return "elevenlabs";if(process.env.AZURE_SPEECH_KEY&&process.env.AZURE_SPEECH_REGION)return "azure";if(process.env.OPENAI_API_KEY)return "openai";return "browser"}
async function openAi(input:SpeechRequest){if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"OpenAI speech provider needs OPENAI_API_KEY in .env.local."},{status:503});const voices=["alloy","ash","ballad","coral","echo","fable","nova","onyx","sage","shimmer","verse"],voice=voices.includes(input.voice||"")?input.voice:"coral",mode=input.language==="hi-IN"?"native Hindi":input.language==="auto"?"natural Indian Hinglish":"Indian English";const response=await fetch("https://api.openai.com/v1/audio/speech",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_TTS_MODEL||"gpt-4o-mini-tts",voice,input:input.text!.slice(0,4000),speed:clamp(input.speed,.8,1.2,.98),instructions:`Warm, calm, premium female assistant speaking ${mode}. Natural emotion and pacing. Pitch preference ${clamp(input.pitch,.5,2,1)}. Volume preference ${clamp(input.volume,0,1,1)}.`,response_format:"mp3"})});return audioResponse(response,"OpenAI")}
async function elevenLabs(input:SpeechRequest){if(!process.env.ELEVENLABS_API_KEY)return NextResponse.json({error:"ElevenLabs is not configured."},{status:503});if(!input.voice)return NextResponse.json({error:"Select an ElevenLabs voice."},{status:400});const response=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(input.voice)}?output_format=mp3_44100_128`,{method:"POST",headers:{"xi-api-key":process.env.ELEVENLABS_API_KEY,"Content-Type":"application/json","Accept":"audio/mpeg"},body:JSON.stringify({text:input.text!.slice(0,10000),model_id:process.env.ELEVENLABS_MODEL||"eleven_flash_v2_5",voice_settings:{stability:.48,similarity_boost:.78,style:.2,use_speaker_boost:true,speed:clamp(input.speed,.7,1.2,1)}})});return audioResponse(response,"ElevenLabs")}
async function azure(input:SpeechRequest){if(!process.env.AZURE_SPEECH_KEY||!process.env.AZURE_SPEECH_REGION)return NextResponse.json({error:"Azure Speech is not configured."},{status:503});if(!input.voice)return NextResponse.json({error:"Select an Azure voice."},{status:400});const locale=input.language==="hi-IN"?"hi-IN":"en-IN",rate=Math.round((clamp(input.speed,.5,1.5,1)-1)*100),pitch=Math.round((clamp(input.pitch,.5,1.5,1)-1)*50),volume=Math.round(clamp(input.volume,0,1,1)*100),ssml=`<speak version="1.0" xml:lang="${locale}"><voice name="${xml(input.voice)}"><prosody rate="${rate}%" pitch="${pitch}%" volume="${volume}">${xml(input.text!)}</prosody></voice></speak>`,response=await fetch(`https://${process.env.AZURE_SPEECH_REGION}.tts.speech.microsoft.com/cognitiveservices/v1`,{method:"POST",headers:{"Ocp-Apim-Subscription-Key":process.env.AZURE_SPEECH_KEY,"Content-Type":"application/ssml+xml","X-Microsoft-OutputFormat":"audio-24khz-48kbitrate-mono-mp3","User-Agent":"KarvianVault"},body:ssml});return audioResponse(response,"Azure")}
async function audioResponse(response:Response,name:string){if(!response.ok){console.error(`${name} TTS`,response.status,await response.text());return NextResponse.json({error:`${name} speech request failed.`},{status:502})}return new Response(response.body,{headers:{"Content-Type":response.headers.get("content-type")||"audio/mpeg","Cache-Control":"no-store"}})}
function clamp(value:number|undefined,min:number,max:number,fallback:number){return Math.max(min,Math.min(max,Number.isFinite(value)?Number(value):fallback))}
function xml(value:string){return value.replace(/[<>&"']/g,character=>({"<":"&lt;",">":"&gt;","&":"&amp;","\"":"&quot;","'":"&apos;"}[character]!))}
