import { isDemoMode } from "../appMode";import { db } from "../db";import type { Priority,ProjectStatus,TaskStatus } from "../types";import type { KyraRuntimeContext,KyraToolResult } from "./types";
export class ToolEngine{
 async execute(input:string,context:KyraRuntimeContext):Promise<KyraToolResult>{const project=input.match(/(?:create|add|make) (?:a )?project(?: named| called)?\s+(.+)/i);if(project){if(isDemoMode)return {handled:true,text:"Public Demo is read-only. Project creation is available in the private owner version.",navigate:"/projects"};const now=new Date().toISOString(),name=clean(project[1]);await db.projects.add({id:`project_${crypto.randomUUID()}`,name,description:"Created by KYRA",status:"planning" as ProjectStatus,priority:"medium" as Priority,progress:0,deadline:now.slice(0,10),tags:["kyra"],createdAt:now,updatedAt:now});return {handled:true,text:`Created ${name}.`,navigate:"/projects"}}
 const task=input.match(/(?:create|add|make) (?:a )?task(?: named| called| to)?\s+(.+)/i);if(task){if(isDemoMode)return {handled:true,text:"Public Demo is read-only. Task creation is available in the private owner version.",navigate:"/tasks"};const now=new Date().toISOString(),title=clean(task[1]);await db.tasks.add({id:`task_${crypto.randomUUID()}`,projectId:"",title,status:"backlog" as TaskStatus,priority:"medium" as Priority,due:now.slice(0,10),description:"Created by KYRA",createdAt:now,updatedAt:now});return {handled:true,text:`Created task: ${title}.`,navigate:"/tasks"}}
 if(/search|find|show|open/i.test(input)&&/notes?/i.test(input)){const term=searchTerm(input,"notes?"),items=context.state.notes.filter(note=>!term||`${note.title} ${note.content}`.toLowerCase().includes(term));return {handled:true,text:items.length?`Found ${items.length} notes: ${items.slice(0,5).map(item=>item.title).join(", ")}.`:"No matching notes found.",navigate:"/notes"}}
 if(/search|find|show|open/i.test(input)&&/documents?|files?/i.test(input)){const term=searchTerm(input,"documents?|files?"),items=context.state.documents.filter(item=>!term||`${item.name} ${item.notes||""}`.toLowerCase().includes(term));return {handled:true,text:items.length?`Found ${items.length} documents: ${items.slice(0,5).map(item=>item.name).join(", ")}.`:"No matching documents found.",navigate:"/documents"}}
 if(/search|find|show|open/i.test(input)&&/(gpt|claude).*chat|chat/i.test(input)){const term=searchTerm(input,"gpt|claude|chats?"),items=context.state.chats.filter(item=>!term||`${item.title} ${item.summary}`.toLowerCase().includes(term));return {handled:true,text:items.length?`Found ${items.length} chats: ${items.slice(0,5).map(item=>item.title).join(", ")}.`:"No matching chats found.",navigate:"/ai-vault"}}
 if(/search|find|show|open/i.test(input)&&/password|credential|secret/i.test(input)){const term=searchTerm(input,"passwords?|credentials?|secrets?"),items=context.state.credentials.filter(item=>!term||`${item.name} ${item.category}`.toLowerCase().includes(term));return {handled:true,text:items.length?`Found ${items.length} matching credentials. Opening the encrypted Vault.`:"No matching credential names found.",navigate:"/vault"}}
 return {handled:false}}
}
function clean(value:string){return value.replace(/[.!?]+$/,"").trim().slice(0,120)}
function searchTerm(input:string,nouns:string){return input.toLowerCase().replace(new RegExp(`search|find|show|open|my|the|about|${nouns}`,"g"),"").trim()}
